// Course data for the learning website

// Featured courses displayed on the homepage
export const featuredCourses = [
  {
    id: 1,
    title: 'Web Development Fundamentals',
    description: 'Learn the core technologies that power the web: HTML, CSS, and JavaScript. This comprehensive course takes you from beginner to proficient web developer.',
    category: 'Web Development',
    level: 'Beginner',
    lessons: 24,
    duration: '12 hours',
    popular: true,
    isNew: false,
    trending: true,
    image: 'web-dev'
  },
  {
    id: 2,
    title: 'Data Science with Python',
    description: 'Master the essential skills of data analysis, visualization, and machine learning using Python, Pandas, NumPy, and Scikit-learn.',
    category: 'Data Science',
    level: 'Intermediate',
    lessons: 32,
    duration: '18 hours',
    popular: true,
    isNew: false,
    trending: true,
    image: 'data-science'
  },
  {
    id: 3,
    title: 'React.js for Beginners',
    description: 'Learn React.js from scratch and build modern, interactive web applications with the most popular JavaScript library.',
    category: 'Web Development',
    level: 'Intermediate',
    lessons: 28,
    duration: '15 hours',
    popular: true,
    isNew: true,
    trending: true,
    image: 'react'
  },
  {
    id: 4,
    title: 'Digital Marketing Strategy',
    description: 'Develop comprehensive digital marketing strategies that drive traffic, engagement, and conversions for businesses of all sizes.',
    category: 'Marketing',
    level: 'Beginner',
    lessons: 20,
    duration: '10 hours',
    popular: false,
    isNew: true,
    trending: false,
    image: 'marketing'
  },
];

// Full course catalog
export const courses = [
  ...featuredCourses,
  {
    id: 5,
    title: 'UX/UI Design Principles',
    description: 'Learn the fundamentals of user experience and interface design. Create beautiful, intuitive designs that users love.',
    category: 'Design',
    level: 'Beginner',
    lessons: 18,
    duration: '9 hours',
    popular: false,
    isNew: false,
    trending: false,
    image: 'design'
  },
  {
    id: 6,
    title: 'Advanced JavaScript Patterns',
    description: 'Take your JavaScript skills to the next level with advanced patterns, functional programming concepts, and modern ES6+ features.',
    category: 'Web Development',
    level: 'Advanced',
    lessons: 22,
    duration: '14 hours',
    popular: true,
    isNew: false,
    trending: false,
    image: 'js-advanced'
  },
  {
    id: 7,
    title: 'iOS App Development with Swift',
    description: 'Build native iOS applications using Swift and Xcode. Learn app architecture, UI design, and how to publish to the App Store.',
    category: 'Mobile Development',
    level: 'Intermediate',
    lessons: 30,
    duration: '16 hours',
    popular: false,
    isNew: true,
    trending: false,
    image: 'ios-dev'
  },
  {
    id: 8,
    title: 'Machine Learning Fundamentals',
    description: 'An introduction to machine learning concepts, algorithms, and practical applications in Python.',
    category: 'Data Science',
    level: 'Intermediate',
    lessons: 26,
    duration: '15 hours',
    popular: true,
    isNew: false,
    trending: true,
    image: 'ml'
  },
  {
    id: 9,
    title: 'Cloud Computing with AWS',
    description: 'Learn to architect, deploy, and manage applications using Amazon Web Services (AWS) cloud infrastructure.',
    category: 'Cloud Computing',
    level: 'Intermediate',
    lessons: 24,
    duration: '13 hours',
    popular: false,
    isNew: false,
    trending: false,
    image: 'aws'
  },
  {
    id: 10,
    title: 'Graphic Design Masterclass',
    description: 'Master the principles of graphic design and learn to use industry-standard tools like Adobe Photoshop and Illustrator.',
    category: 'Design',
    level: 'Beginner',
    lessons: 32,
    duration: '18 hours',
    popular: false,
    isNew: false,
    trending: false,
    image: 'graphic-design'
  },
  {
    id: 11,
    title: 'Project Management Professional',
    description: 'Prepare for PMP certification with comprehensive coverage of project management methodologies, tools, and best practices.',
    category: 'Business',
    level: 'Advanced',
    lessons: 40,
    duration: '24 hours',
    popular: true,
    isNew: false,
    trending: true,
    image: 'pmp'
  },
  {
    id: 12,
    title: 'Android Development with Kotlin',
    description: 'Build modern Android applications using Kotlin, Android Studio, and the latest architecture components.',
    category: 'Mobile Development',
    level: 'Intermediate',
    lessons: 28,
    duration: '16 hours',
    popular: false,
    isNew: true,
    trending: false,
    image: 'android'
  },
  {
    id: 13,
    title: 'Digital Photography Fundamentals',
    description: 'Learn the art and science of photography, from camera basics to composition, lighting, and post-processing.',
    category: 'Photography',
    level: 'Beginner',
    lessons: 22,
    duration: '10 hours',
    popular: false,
    isNew: false,
    trending: false,
    image: 'photography'
  },
  {
    id: 14,
    title: 'Full-Stack Development with MERN',
    description: 'Master the MERN stack (MongoDB, Express, React, Node.js) to build full-stack web applications from start to finish.',
    category: 'Web Development',
    level: 'Advanced',
    lessons: 45,
    duration: '30 hours',
    popular: true,
    isNew: false,
    trending: true,
    image: 'mern'
  },
  {
    id: 15,
    title: 'SEO and Content Marketing',
    description: 'Learn search engine optimization strategies and content marketing techniques to drive organic traffic to websites.',
    category: 'Marketing',
    level: 'Intermediate',
    lessons: 20,
    duration: '12 hours',
    popular: false,
    isNew: false,
    trending: false,
    image: 'seo'
  },
];